// <auto-generated />
using System;
using ClickNCheck.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClickNCheck.Migrations
{
    [DbContext(typeof(ClickNCheckContext))]
    [Migration("20190214093400_initCreate")]
    partial class initCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClickNCheck.Models.Candidate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("ID_Passport");

                    b.Property<string>("ID_Type");

                    b.Property<string>("Maiden_Surname");

                    b.Property<string>("Name");

                    b.Property<int?>("OrganisationID");

                    b.Property<string>("Phone");

                    b.Property<int?>("RecruiterID");

                    b.Property<string>("Surname");

                    b.HasKey("ID");

                    b.HasIndex("OrganisationID");

                    b.HasIndex("RecruiterID");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("ClickNCheck.Models.Candidate_JobProfile", b =>
                {
                    b.Property<int>("CandidateId");

                    b.Property<int>("JobProfileId");

                    b.HasKey("CandidateId", "JobProfileId");

                    b.HasIndex("JobProfileId");

                    b.ToTable("Candidate_JobProfile");
                });

            modelBuilder.Entity("ClickNCheck.Models.Checks", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cost");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("TurnaraoundTime");

                    b.HasKey("ID");

                    b.ToTable("Checks");
                });

            modelBuilder.Entity("ClickNCheck.Models.JobProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("OrganisationID");

                    b.Property<string>("Title");

                    b.Property<bool>("isCompleted");

                    b.HasKey("ID");

                    b.HasIndex("OrganisationID");

                    b.ToTable("JobProfile");
                });

            modelBuilder.Entity("ClickNCheck.Models.JobProfile_Checks", b =>
                {
                    b.Property<int>("ChecksId");

                    b.Property<int>("JobProfileId");

                    b.Property<int>("order");

                    b.HasKey("ChecksId", "JobProfileId");

                    b.HasIndex("JobProfileId");

                    b.ToTable("JobProfile_Checks");
                });

            modelBuilder.Entity("ClickNCheck.Models.LinkCode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Admin_ID");

                    b.Property<int?>("AdministratorID");

                    b.Property<string>("Code");

                    b.Property<bool>("Used");

                    b.HasKey("ID");

                    b.HasIndex("AdministratorID");

                    b.ToTable("LinkCodes");
                });

            modelBuilder.Entity("ClickNCheck.Models.Organisation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Organisation");
                });

            modelBuilder.Entity("ClickNCheck.Models.Recruiter_JobProfile", b =>
                {
                    b.Property<int>("RecruiterId");

                    b.Property<int>("JobProfileId");

                    b.HasKey("RecruiterId", "JobProfileId");

                    b.HasIndex("JobProfileId");

                    b.ToTable("Recruiter_JobProfile");
                });

            modelBuilder.Entity("ClickNCheck.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("EmployeeNumber");

                    b.Property<int>("ManagerID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("OrganisationID");

                    b.Property<int>("Otp");

                    b.Property<string>("Password");

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("Salt");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.Property<int>("UserType");

                    b.Property<int?>("userID");

                    b.HasKey("ID");

                    b.HasIndex("OrganisationID");

                    b.HasIndex("userID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ClickNCheck.Models.Candidate", b =>
                {
                    b.HasOne("ClickNCheck.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationID");

                    b.HasOne("ClickNCheck.Models.User", "Recruiter")
                        .WithMany()
                        .HasForeignKey("RecruiterID");
                });

            modelBuilder.Entity("ClickNCheck.Models.Candidate_JobProfile", b =>
                {
                    b.HasOne("ClickNCheck.Models.Candidate", "Candidate")
                        .WithMany("Candidate_JobProfile")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClickNCheck.Models.JobProfile", "JobProfile")
                        .WithMany("Candidate_JobProfile")
                        .HasForeignKey("JobProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClickNCheck.Models.JobProfile", b =>
                {
                    b.HasOne("ClickNCheck.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationID");
                });

            modelBuilder.Entity("ClickNCheck.Models.JobProfile_Checks", b =>
                {
                    b.HasOne("ClickNCheck.Models.Checks", "Checks")
                        .WithMany("JobProfile_Checks")
                        .HasForeignKey("ChecksId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClickNCheck.Models.JobProfile", "JobProfile")
                        .WithMany("JobProfile_Checks")
                        .HasForeignKey("JobProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClickNCheck.Models.LinkCode", b =>
                {
                    b.HasOne("ClickNCheck.Models.User", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorID");
                });

            modelBuilder.Entity("ClickNCheck.Models.Recruiter_JobProfile", b =>
                {
                    b.HasOne("ClickNCheck.Models.JobProfile", "JobProfile")
                        .WithMany("Recruiter_JobProfile")
                        .HasForeignKey("JobProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClickNCheck.Models.User", "Recruiter")
                        .WithMany("Recruiter_JobProfile")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClickNCheck.Models.User", b =>
                {
                    b.HasOne("ClickNCheck.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClickNCheck.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userID");
                });
#pragma warning restore 612, 618
        }
    }
}
